// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ledger.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Parse pasted CSV text into ImportRow records under one batch.
 * The format is deliberately forgiving, because the text is arriving from a
 * clipboard rather than from a contract:
 * Delimiter    comma, semicolon or tab, detected from the first line, or
 * forced by passing one character (or the word 'tab')
 * Quotes       standard CSV: "..." with "" for a literal quote, and a
 * newline inside quotes stays inside the field
 * Header       detected by looking for a known column name in the first row.
 * When present, columns are mapped by name and may be in any
 * order; when absent, the order is
 * date, merchant, description, amount, account, category
 * Names        English and Dutch headers both map — date/datum,
 * amount/bedrag, account/rekening, category/categorie, and so on
 * Amounts      currency symbols and spaces are stripped, and both decimal
 * conventions are read: 1.234,56 and 1,234.56 both give 1234.56
 * Blank lines  skipped, wherever they are
 * A line that cannot be read into columns still lands, flagged, carrying the
 * reason and the line itself. That is the loader table doing its job: a parse
 * failure belongs in the reject list beside the validation failures, not in an
 * error dialog that loses the other ninety-nine rows.
 * THE SIGN IS DISCARDED. ImportRow.Amount is always positive here, because
 * direction comes from the category everywhere else in this app. A statement
 * export writing -61.20 for a payment lands as 61.20, and Groceries makes it a
 * payment. This is the one place a paste could surprise someone, so it is
 * stated on the screen as well.
 * @param Csv The pasted text
 * @param Batch Batch key to land under; existing rows are not touched
 * @param Delimiter One character, the word 'tab', or empty to detect it
 * @returns Rows landed, including the ones flagged as unparseable
 */
public class CSV_LandImportRows extends UserAction<java.lang.Long>
{
	private final java.lang.String Csv;
	private final java.lang.String Batch;
	private final java.lang.String Delimiter;

	public CSV_LandImportRows(
		IContext context,
		java.lang.String _csv,
		java.lang.String _batch,
		java.lang.String _delimiter
	)
	{
		super(context);
		this.Csv = _csv;
		this.Batch = _batch;
		this.Delimiter = _delimiter;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE

		if (Csv == null || Csv.trim().isEmpty()) {
		    return 0L;
		}
		
		final int MAX_ROWS = 5000;
		
		String text = Csv;
		if (!text.isEmpty() && text.charAt(0) == '﻿') {
		    text = text.substring(1);
		}
		
		// --- delimiter -----------------------------------------------------------
		char delim;
		String forced = (Delimiter == null ? "" : Delimiter.trim());
		if (forced.equalsIgnoreCase("tab")) {
		    delim = '\t';
		} else if (forced.length() == 1) {
		    delim = forced.charAt(0);
		} else {
		    // Count candidates on the first line only, outside quotes. A semicolon
		    // export full of commas inside quoted descriptions would otherwise look
		    // comma-separated.
		    int commas = 0, semis = 0, tabs = 0;
		    boolean q = false;
		    for (int i = 0; i < text.length(); i++) {
		        char ch = text.charAt(i);
		        if (ch == '"') { q = !q; continue; }
		        if (!q && (ch == '\n' || ch == '\r')) break;
		        if (q) continue;
		        if (ch == ',') commas++;
		        else if (ch == ';') semis++;
		        else if (ch == '\t') tabs++;
		    }
		    if (semis > commas && semis >= tabs) delim = ';';
		    else if (tabs > commas && tabs > semis) delim = '\t';
		    else delim = ',';
		}
		
		// --- records -------------------------------------------------------------
		// One pass over the characters. inQuotes is the whole reason this is not a
		// split on newline followed by a split on the delimiter.
		java.util.List<java.util.List<String>> records = new java.util.ArrayList<java.util.List<String>>();
		java.util.List<String> row = new java.util.ArrayList<String>();
		StringBuilder cell = new StringBuilder();
		boolean inQuotes = false;
		
		for (int i = 0; i < text.length(); i++) {
		    char ch = text.charAt(i);
		    if (inQuotes) {
		        if (ch == '"') {
		            if (i + 1 < text.length() && text.charAt(i + 1) == '"') { cell.append('"'); i++; }
		            else inQuotes = false;
		        } else {
		            cell.append(ch);
		        }
		        continue;
		    }
		    if (ch == '"') { inQuotes = true; continue; }
		    if (ch == delim) { row.add(cell.toString()); cell.setLength(0); continue; }
		    if (ch == '\r' || ch == '\n') {
		        if (ch == '\r' && i + 1 < text.length() && text.charAt(i + 1) == '\n') i++;
		        row.add(cell.toString());
		        cell.setLength(0);
		        records.add(row);
		        row = new java.util.ArrayList<String>();
		        continue;
		    }
		    cell.append(ch);
		}
		row.add(cell.toString());
		records.add(row);
		
		// Blank lines anywhere, including a trailing newline, are not rows.
		java.util.List<java.util.List<String>> data = new java.util.ArrayList<java.util.List<String>>();
		for (java.util.List<String> r : records) {
		    for (String v : r) {
		        if (v != null && !v.trim().isEmpty()) { data.add(r); break; }
		    }
		}
		if (data.isEmpty()) {
		    return 0L;
		}
		
		// --- column map ----------------------------------------------------------
		java.util.function.Function<String, String> norm = v ->
		    v == null ? "" : v.trim().toLowerCase().replaceAll("[^a-z0-9]", "");
		
		int iDate = 0, iMerchant = 1, iDesc = 2, iAmount = 3, iAccount = 4, iCategory = 5;
		int iMerchant2 = -1, iDesc2 = -1, iDesc3 = -1;
		int firstDataRow = 0;
		
		java.util.List<String> head = data.get(0);
		
		// --- bank format -----------------------------------------------------
		// A statement export is not a generic CSV with different column names. The
		// date format, the decimal convention, and where the counterparty's NAME
		// lives as opposed to its ACCOUNT NUMBER all change together, so the format
		// is recognised once and drives all of them.
		//
		// Detection is on a pair of columns rather than one, because single names
		// are not distinctive: 'Datum' and 'Bedrag' appear in every Dutch export
		// there is. What is distinctive is ING's Af/Bij direction column and
		// Rabobank's separate counterparty-name column.
		//
		// Falling through to 'generic' is always safe: it is the header-name mapping
		// that already worked, and a file that matches neither signature is read
		// exactly as it was before this existed.
		java.util.Set<String> hset = new java.util.HashSet<String>();
		for (String v : head) hset.add(norm.apply(v));
		
		String bank = "generic";
		if (hset.contains("afbij") && (hset.contains("naamomschrijving") || hset.contains("bedrageur"))) {
		    bank = "ing";
		} else if (hset.contains("naamtegenpartij") && (hset.contains("ibanbban") || hset.contains("volgnummer"))) {
		    bank = "rabobank";
		}
		
		boolean looksLikeHeader = false;
		for (String v : head) {
		    String n = norm.apply(v);
		    if (n.equals("date") || n.equals("datum") || n.equals("txdate")
		        || n.equals("transactiondate") || n.equals("boekingsdatum")
		        || n.equals("merchant") || n.equals("payee") || n.equals("counterparty")
		        || n.equals("amount") || n.equals("bedrag")
		        || n.equals("account") || n.equals("rekening")
		        || n.equals("category") || n.equals("categorie")
		        || n.equals("description") || n.equals("omschrijving")) {
		        looksLikeHeader = true;
		        break;
		    }
		}
		
		if (!bank.equals("generic")) {
		    // Named formats map by exact column, not by the alias list. Two of the
		    // aliases would actively mislead here: 'tegenrekening' is in the merchant
		    // list, and in an ING export that column is the counterparty's IBAN while
		    // the name sits in 'Naam / Omschrijving' — the generic map would file an
		    // account number as the merchant on every row and nothing would flag it.
		    iDate = -1; iMerchant = -1; iDesc = -1; iAmount = -1; iAccount = -1; iCategory = -1;
		    for (int i = 0; i < head.size(); i++) {
		        String n = norm.apply(head.get(i));
		        if (bank.equals("ing")) {
		            if (n.equals("datum")) iDate = i;
		            else if (n.equals("naamomschrijving")) iMerchant = i;
		            else if (n.equals("mededelingen")) iDesc = i;
		            else if (n.equals("mutatiesoort")) iDesc2 = i;
		            else if (n.equals("bedrageur") || n.equals("bedrag")) iAmount = i;
		            else if (n.equals("rekening")) iAccount = i;
		        } else {
		            if (n.equals("datum")) iDate = i;              // not 'rentedatum'
		            else if (n.equals("naamtegenpartij")) iMerchant = i;
		            else if (n.equals("naamtegenpartijtoevoeging")) iMerchant2 = i;
		            else if (n.equals("omschrijving1")) iDesc = i;
		            else if (n.equals("omschrijving2")) iDesc2 = i;
		            else if (n.equals("omschrijving3")) iDesc3 = i;
		            else if (n.equals("bedrag")) iAmount = i;       // not 'saldonamutatie'
		            else if (n.equals("ibanbban")) iAccount = i;
		        }
		    }
		    firstDataRow = 1;
		} else if (looksLikeHeader) {
		    iDate = -1; iMerchant = -1; iDesc = -1; iAmount = -1; iAccount = -1; iCategory = -1;
		    for (int i = 0; i < head.size(); i++) {
		        String n = norm.apply(head.get(i));
		        if (iDate < 0 && (n.equals("date") || n.equals("datum") || n.equals("txdate")
		            || n.equals("txdatetext") || n.equals("transactiondate") || n.equals("boekingsdatum"))) {
		            iDate = i;
		        } else if (iMerchant < 0 && (n.equals("merchant") || n.equals("payee")
		            || n.equals("counterparty") || n.equals("naam") || n.equals("name")
		            || n.equals("tegenrekening"))) {
		            iMerchant = i;
		        } else if (iDesc < 0 && (n.equals("description") || n.equals("omschrijving")
		            || n.equals("mededelingen") || n.equals("memo") || n.equals("notes"))) {
		            iDesc = i;
		        } else if (iAmount < 0 && (n.equals("amount") || n.equals("bedrag") || n.equals("value"))) {
		            iAmount = i;
		        } else if (iAccount < 0 && (n.equals("account") || n.equals("accountname")
		            || n.equals("rekening") || n.equals("iban"))) {
		            iAccount = i;
		        } else if (iCategory < 0 && (n.equals("category") || n.equals("categoryname")
		            || n.equals("categorie"))) {
		            iCategory = i;
		        }
		    }
		    firstDataRow = 1;
		}
		
		// --- helpers -------------------------------------------------------------
		java.util.function.BiFunction<java.util.List<String>, Integer, String> at = (rec, idx) ->
		    (idx == null || idx < 0 || idx >= rec.size() || rec.get(idx) == null)
		        ? "" : rec.get(idx).trim();
		
		java.util.function.BiFunction<String, Integer, String> clip = (v, n) ->
		    v == null ? "" : (v.length() <= n ? v : v.substring(0, n));
		
		// Dates are normalised HERE, not in the promote step. The row lands as text
		// and PROMOTE_ImportBatch reads it with DATEPARSE(TxDateText, 'yyyy-MM-dd'),
		// one format for every source — so the place that knows which format arrived
		// is the place that has to convert it. ING writes 20260824; teaching the OQL
		// a second pattern would mean a second statement over the whole batch and a
		// rule for deciding which one applies.
		//
		// Anything not recognised is passed through UNCHANGED rather than rejected:
		// the row still lands, DATEPARSE returns null, and the existing empty-date
		// check flags it with a message about the date. Guessing here would turn a
		// visible bad date into an invisible wrong one.
		java.util.function.Function<String, String> isoDate = raw -> {
		    if (raw == null) return "";
		    String v = raw.trim();
		    if (v.length() == 8 && v.chars().allMatch(Character::isDigit)) {
		        return v.substring(0, 4) + "-" + v.substring(4, 6) + "-" + v.substring(6, 8);
		    }
		    // dd-MM-yyyy and dd/MM/yyyy — day first is the Dutch convention, and no
		    // export in scope here writes month first.
		    if (v.length() == 10 && (v.charAt(2) == '-' || v.charAt(2) == '/')
		        && (v.charAt(5) == '-' || v.charAt(5) == '/')) {
		        return v.substring(6, 10) + "-" + v.substring(3, 5) + "-" + v.substring(0, 2);
		    }
		    return v;
		};
		
		// Join the parts a bank splits across columns, dropping the empty ones so a
		// description never comes back as ' ·  · ' when only the first part is filled.
		java.util.function.Function<java.util.List<String>, String> joinParts = parts -> {
		    StringBuilder sb = new StringBuilder();
		    for (String s : parts) {
		        if (s == null) continue;
		        String t = s.trim();
		        if (t.isEmpty()) continue;
		        if (sb.length() > 0) sb.append(" · ");
		        sb.append(t);
		    }
		    return sb.toString();
		};
		
		// Both decimal conventions, and neither is guessed from a locale: whichever
		// separator appears last is the decimal one, because that is true in both.
		java.util.function.Function<String, java.math.BigDecimal> money = raw -> {
		    if (raw == null) return null;
		    StringBuilder digits = new StringBuilder();
		    for (int i = 0; i < raw.length(); i++) {
		        char ch = raw.charAt(i);
		        if ((ch >= '0' && ch <= '9') || ch == '.' || ch == ',') digits.append(ch);
		    }
		    String t = digits.toString();
		    if (t.isEmpty()) return null;
		
		    int lastDot = t.lastIndexOf('.');
		    int lastComma = t.lastIndexOf(',');
		    if (lastDot >= 0 && lastComma >= 0) {
		        if (lastComma > lastDot) t = t.replace(".", "").replace(',', '.');
		        else t = t.replace(",", "");
		    } else if (lastComma >= 0) {
		        // A lone comma is a decimal point when it has one or two digits behind
		        // it (61,2 / 61,20) and a thousands separator otherwise (1,234).
		        int after = t.length() - lastComma - 1;
		        if (after == 1 || after == 2) t = t.replace(',', '.');
		        else t = t.replace(",", "");
		    } else if (lastDot >= 0 && t.indexOf('.') != lastDot) {
		        // 1.234.56 — every dot but the last is grouping.
		        t = t.substring(0, lastDot).replace(".", "") + "." + t.substring(lastDot + 1);
		    }
		
		    try {
		        // The sign is already gone: the filter above keeps only digits, '.' and
		        // ',', so a minus or a bracketed negative never reaches here and t
		        // cannot parse negative. abs() is therefore unreachable today — it is
		        // kept as a guard for the one edit that would reintroduce a sign, which
		        // is widening that filter to carry '-' through. Mutation testing found
		        // this: removing abs() breaks no test, because the filter is what the
		        // "a negative amount lands positive" test is really exercising.
		        return new java.math.BigDecimal(t).abs();
		    } catch (NumberFormatException e) {
		        return null;
		    }
		};
		
		// --- land ----------------------------------------------------------------
		com.mendix.systemwideinterfaces.core.IContext ctx = getContext();
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixObject> landed =
		    new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixObject>();
		long rowNo = 0;
		int ignored = 0;
		
		for (int r = firstDataRow; r < data.size(); r++) {
		    if (landed.size() >= MAX_ROWS) { ignored = data.size() - r; break; }
		    java.util.List<String> rec = data.get(r);
		    rowNo++;
		
		    com.mendix.systemwideinterfaces.core.IMendixObject o =
		        com.mendix.core.Core.instantiate(ctx, "Ledger.ImportRow");
		    o.setValue(ctx, "Batch", Batch);
		    o.setValue(ctx, "RowNo", Long.valueOf(rowNo));
		    String mMerchant = at.apply(rec, iMerchant);
		    if (iMerchant2 >= 0) {
		        mMerchant = joinParts.apply(java.util.Arrays.asList(mMerchant, at.apply(rec, iMerchant2)));
		    }
		    String mDesc = at.apply(rec, iDesc);
		    if (iDesc2 >= 0 || iDesc3 >= 0) {
		        mDesc = joinParts.apply(java.util.Arrays.asList(
		            mDesc, at.apply(rec, iDesc2), at.apply(rec, iDesc3)));
		    }
		
		    o.setValue(ctx, "TxDateText", clip.apply(isoDate.apply(at.apply(rec, iDate)), 30));
		    o.setValue(ctx, "Merchant", clip.apply(mMerchant, 200));
		    o.setValue(ctx, "Description", clip.apply(mDesc, 500));
		    o.setValue(ctx, "AccountName", clip.apply(at.apply(rec, iAccount), 100));
		    o.setValue(ctx, "CategoryName", clip.apply(at.apply(rec, iCategory), 100));
		
		    String why = null;
		    java.math.BigDecimal amount = null;
		    if (rec.size() < 2) {
		        why = "Expected at least 2 columns, found " + rec.size();
		    } else if (iAmount < 0) {
		        why = "No amount column found in the header";
		    } else {
		        amount = money.apply(at.apply(rec, iAmount));
		        if (amount == null) {
		            why = "Amount could not be read from '" + at.apply(rec, iAmount) + "'";
		        }
		    }
		
		    if (why == null) {
		        o.setValue(ctx, "Amount", amount);
		        o.setValue(ctx, "IsValid", Boolean.TRUE);
		        o.setValue(ctx, "HasParseError", Boolean.FALSE);
		        o.setValue(ctx, "Problem", "");
		    } else {
		        StringBuilder line = new StringBuilder();
		        for (int c = 0; c < rec.size(); c++) {
		            if (c > 0) line.append(delim);
		            line.append(rec.get(c));
		        }
		        o.setValue(ctx, "Amount", java.math.BigDecimal.ZERO);
		        o.setValue(ctx, "IsValid", Boolean.FALSE);
		        o.setValue(ctx, "HasParseError", Boolean.TRUE);
		        o.setValue(ctx, "Problem", clip.apply(why + " — " + line.toString(), 200));
		    }
		
		    landed.add(o);
		}
		
		// A cap that says nothing is a cap that reads as "all of it imported".
		if (ignored > 0) {
		    com.mendix.systemwideinterfaces.core.IMendixObject note =
		        com.mendix.core.Core.instantiate(ctx, "Ledger.ImportRow");
		    note.setValue(ctx, "Batch", Batch);
		    note.setValue(ctx, "RowNo", Long.valueOf(rowNo + 1));
		    note.setValue(ctx, "TxDateText", "");
		    note.setValue(ctx, "Merchant", "");
		    note.setValue(ctx, "Description", "");
		    note.setValue(ctx, "AccountName", "");
		    note.setValue(ctx, "CategoryName", "");
		    note.setValue(ctx, "Amount", java.math.BigDecimal.ZERO);
		    note.setValue(ctx, "IsValid", Boolean.FALSE);
		    note.setValue(ctx, "HasParseError", Boolean.TRUE);
		    note.setValue(ctx, "Problem", clip.apply(
		        ignored + " further line(s) were not read: this paste is capped at " + MAX_ROWS + " rows", 200));
		    landed.add(note);
		}
		
		if (!landed.isEmpty()) {
		    com.mendix.core.Core.commit(ctx, landed);
		}
		
		com.mendix.core.Core.getLogger("Import").info(
		    "CSV_LandImportRows: landed " + landed.size() + " row(s) into batch '" + Batch
		    + "' (delimiter '" + delim + "', header " + looksLikeHeader + ")");
		
		return Long.valueOf(landed.size());

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CSV_LandImportRows";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
