// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ledger.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Execute one OQL DML statement. Returns the number of rows affected.
 * This is the primitive the rest of the file builds on. It deliberately has no
 * variables: a statement with variables goes through OQL_ExecuteWith, so the
 * caller has to decide which values are data (bound, escaped) rather than
 * getting a string-concatenation habit for free.
 * WHAT THIS BYPASSES. The statement runs in the database, inside the calling
 * microflow's transaction. It does not go through the object cache, so:
 * * no before/after-commit event handlers fire,
 * * no validation rules run,
 * * an object already retrieved in this context keeps its old values,
 * * a client holding the object is not refreshed.
 * Use it for bulk work over rows nobody is looking at. For a single object a
 * user is editing, change and commit the object.
 * @param Statement An OQL insert, update or delete statement
 * @returns Rows affected
 */
public class OQL_Execute extends UserAction<java.lang.Long>
{
	private final java.lang.String Statement;

	public OQL_Execute(
		IContext context,
		java.lang.String _statement
	)
	{
		super(context);
		this.Statement = _statement;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE

		if (Statement == null || Statement.trim().isEmpty()) {
		    throw new IllegalArgumentException("OQL_Execute: statement is empty");
		}
		com.mendix.datastorage.OqlStatement stmt = com.mendix.core.Core.createOqlStatement(Statement);
		int affected = stmt.execute(getContext());
		com.mendix.core.Core.getLogger("OQL").debug("OQL_Execute affected " + affected + " row(s): " + Statement);
		return (long) affected;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "OQL_Execute";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
