// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ledger.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Run a statement and report what happened instead of throwing.
 * Returns 'OK rows=N' or 'ERR <exception>: <message>'. This exists because the
 * grammar OQL DML accepts is not documented anywhere the model can see, so
 * finding out what a statement does is an experiment, and an experiment that
 * rolls the transaction back on the first surprise is a slow experiment.
 * Not for production paths: a failure that returns a string is a failure the
 * caller can ignore. Use OQL_Execute there and let it throw.
 * @param Statement An OQL statement to try
 * @returns 'OK rows=N' or 'ERR ...'
 */
public class OQL_Try extends UserAction<java.lang.String>
{
	private final java.lang.String Statement;

	public OQL_Try(
		IContext context,
		java.lang.String _statement
	)
	{
		super(context);
		this.Statement = _statement;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE

		try {
		    com.mendix.datastorage.OqlStatement stmt = com.mendix.core.Core.createOqlStatement(Statement);
		    int affected = stmt.execute(getContext());
		    return "OK rows=" + affected;
		} catch (Throwable t) {
		    String message = String.valueOf(t.getMessage()).replace('\n', ' ').replace('\r', ' ');
		    if (message.length() > 300) {
		        message = message.substring(0, 300) + "...";
		    }
		    return "ERR " + t.getClass().getSimpleName() + ": " + message;
		}

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "OQL_Try";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
