// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ledger.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Execute one OQL DML statement carrying up to four bound variables.
 * Variables are written $Name in the statement and bound here by name, so a
 * value never becomes part of the statement text. That matters for the same
 * reason it matters in SQL: a merchant called O'Brien breaks a concatenated
 * statement and does not break a bound one.
 * Types are declared rather than guessed. A slot with an empty name is skipped,
 * which is what makes one action serve a statement with one variable and a
 * statement with four.
 * @param Statement An OQL insert, update or delete statement using $Name variables
 * @param Name1 Variable name without the $, or empty to skip
 * @param Value1 The value, as text; converted according to Type1
 * @param Type1 'string', 'integer', 'decimal', 'boolean', 'datetime' or 'id'
 * @returns Rows affected
 */
public class OQL_ExecuteWith extends UserAction<java.lang.Long>
{
	private final java.lang.String Statement;
	private final java.lang.String Name1;
	private final java.lang.String Value1;
	private final java.lang.String Type1;
	private final java.lang.String Name2;
	private final java.lang.String Value2;
	private final java.lang.String Type2;
	private final java.lang.String Name3;
	private final java.lang.String Value3;
	private final java.lang.String Type3;
	private final java.lang.String Name4;
	private final java.lang.String Value4;
	private final java.lang.String Type4;

	public OQL_ExecuteWith(
		IContext context,
		java.lang.String _statement,
		java.lang.String _name1,
		java.lang.String _value1,
		java.lang.String _type1,
		java.lang.String _name2,
		java.lang.String _value2,
		java.lang.String _type2,
		java.lang.String _name3,
		java.lang.String _value3,
		java.lang.String _type3,
		java.lang.String _name4,
		java.lang.String _value4,
		java.lang.String _type4
	)
	{
		super(context);
		this.Statement = _statement;
		this.Name1 = _name1;
		this.Value1 = _value1;
		this.Type1 = _type1;
		this.Name2 = _name2;
		this.Value2 = _value2;
		this.Type2 = _type2;
		this.Name3 = _name3;
		this.Value3 = _value3;
		this.Type3 = _type3;
		this.Name4 = _name4;
		this.Value4 = _value4;
		this.Type4 = _type4;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE

		if (Statement == null || Statement.trim().isEmpty()) {
		    throw new IllegalArgumentException("OQL_ExecuteWith: statement is empty");
		}
		com.mendix.datastorage.OqlStatement stmt = com.mendix.core.Core.createOqlStatement(Statement);
		
		String[] names = { Name1, Name2, Name3, Name4 };
		String[] values = { Value1, Value2, Value3, Value4 };
		String[] types = { Type1, Type2, Type3, Type4 };
		
		for (int i = 0; i < names.length; i++) {
		    String name = names[i];
		    if (name == null || name.trim().isEmpty()) {
		        continue;
		    }
		    String value = values[i];
		    String type = (types[i] == null ? "string" : types[i].trim().toLowerCase());
		    switch (type) {
		        case "integer":
		        case "long":
		            stmt.setVariable(name, Long.parseLong(value.trim()));
		            break;
		        case "decimal":
		            stmt.setVariable(name, new java.math.BigDecimal(value.trim()));
		            break;
		        case "boolean":
		            stmt.setVariable(name, Boolean.parseBoolean(value.trim()));
		            break;
		        case "datetime":
		            // ISO-8601 instant, which is what formatDateTime with a UTC pattern emits.
		            stmt.setVariable(name, java.util.Date.from(java.time.Instant.parse(value.trim())));
		            break;
		        case "id":
		            stmt.setVariable(name,
		                com.mendix.core.Core.createMendixIdentifier(Long.parseLong(value.trim())));
		            break;
		        case "string":
		        default:
		            stmt.setVariable(name, value);
		            break;
		    }
		}
		
		int affected = stmt.execute(getContext());
		com.mendix.core.Core.getLogger("OQL").debug("OQL_ExecuteWith affected " + affected + " row(s): " + Statement);
		return (long) affected;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "OQL_ExecuteWith";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
