// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<boolean>}
 */
export async function ApplyStoredSkin() {
	// BEGIN USER CODE
	var skins = ["ledgerpaper", "ing", "rabobank"];
	var stored = null;
	try {
	    stored = window.localStorage.getItem("mxcli-skin");
	} catch (e) {
	    // No storage available: the default is the right fallback.
	}
	var root = document.documentElement;
	skins.forEach(function (s) { root.classList.remove("mxt-" + s); });
	if (stored !== null && skins.indexOf(stored) !== -1) {
	    root.classList.add("mxt-" + stored);
	}
	return Promise.resolve(true);
	// END USER CODE
}
