// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<boolean>}
 */
export async function ApplyStoredTheme() {
	// BEGIN USER CODE
	var stored = null;
	try {
	    stored = window.localStorage.getItem("mxcli-theme");
	} catch (e) {
	    // No storage available: following the OS is the right fallback.
	}
	var root = document.documentElement;
	root.classList.remove("theme-light", "theme-dark");
	if (stored === "light" || stored === "dark") {
	    root.classList.add("theme-" + stored);
	}
	return Promise.resolve(true);
	// END USER CODE
}
