// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<string>}
 */
export async function CycleAppSkin() {
	// BEGIN USER CODE
	var skins = ["ledgerpaper", "ing", "rabobank"];
	var root = document.documentElement;
	var current = 0;
	for (var i = 0; i < skins.length; i++) {
	    if (root.classList.contains("mxt-" + skins[i])) { current = i; break; }
	}
	var next = skins[(current + 1) % skins.length];
	
	skins.forEach(function (s) { root.classList.remove("mxt-" + s); });
	root.classList.add("mxt-" + next);
	try {
	    window.localStorage.setItem("mxcli-skin", next);
	} catch (e) {
	    // No storage available: the choice still applies for this page view.
	}
	return Promise.resolve(next);
	// END USER CODE
}
