// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} [skin]
 * @returns {Promise.<string>}
 */
export async function SetAppSkin(skin) {
	// BEGIN USER CODE
	// Modelled as Skin, reaches the body as lowercase skin — mxbuild lowers the
	// first letter when it generates the wrapper.
	var skins = ["ledgerpaper", "ing", "rabobank"];
	var root = document.documentElement;
	skins.forEach(function (s) { root.classList.remove("mxt-" + s); });
	
	var chosen = skins.indexOf(skin) === -1 ? "ledgerpaper" : skin;
	root.classList.add("mxt-" + chosen);
	try {
	    window.localStorage.setItem("mxcli-skin", chosen);
	} catch (e) {
	    // No storage available: the choice still applies for this page view.
	}
	return Promise.resolve(chosen);
	// END USER CODE
}
