// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} theme
 * @returns {Promise.<boolean>}
 */
export async function SetAppTheme(theme) {
	// BEGIN USER CODE
	var root = document.documentElement;
		root.classList.remove("theme-light", "theme-dark");
		try {
		    if (theme === "light" || theme === "dark") {
		        root.classList.add("theme-" + theme);
		        window.localStorage.setItem("mxcli-theme", theme);
		    } else {
		        window.localStorage.removeItem("mxcli-theme");
		    }
		} catch (e) {
		    if (theme === "light" || theme === "dark") {
		        root.classList.add("theme-" + theme);
		    }
		}
		return Promise.resolve(true);
	// END USER CODE
}
