// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<string>}
 */
export async function ToggleAppTheme() {
	// BEGIN USER CODE
	var root = document.documentElement;
	var effective;
	if (root.classList.contains("theme-dark")) {
	    effective = "dark";
	} else if (root.classList.contains("theme-light")) {
	    effective = "light";
	} else {
	    effective = window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches
	        ? "dark"
	        : "light";
	}
	var next = effective === "dark" ? "light" : "dark";
	root.classList.remove("theme-light", "theme-dark");
	root.classList.add("theme-" + next);
	try {
	    window.localStorage.setItem("mxcli-theme", next);
	} catch (e) {
	    // Private browsing and some embedded webviews reject storage; the class is
	    // already applied, so the only thing lost is persistence across reloads.
	}
	return Promise.resolve(next);
	// END USER CODE
}
