// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Toggle the sidebar, replacing the marketplace widget the copy cannot carry.
 * The state lives on the SCROLL CONTAINER, not on the layout root — Mendix puts
 * `mx-scrollcontainer-open` there, and this project's own stylesheet already
 * keys off it:
 * .mx-scrollcontainer-shrink:not(.mx-scrollcontainer-open) > .region-sidebar
 * So this flips exactly what the Forms button flips, and the 52px rail rules
 * that were written against that selector keep working untouched.
 * The first attempt toggled `sidebar-open` on `.layout-atlas`, which is a class
 * nothing in the app responds to: the DOM changed, the sidebar did not, and the
 * button looked wired while doing nothing. Worth stating because a class toggle
 * always "succeeds" — there is no error to catch, only a screenshot that looks
 * identical before and after.
 * @returns {Promise.<boolean>}
 */
export async function ToggleAppSidebar() {
	// BEGIN USER CODE
	// The WIDTH is an inline custom property on the region, not a class:
		//   <div class="region-sidebar" style="--sidebar-size: 232px">
		// Two earlier attempts flipped classes instead and both "worked" — the DOM
		// changed, the selector matched, and the sidebar stayed 232px, because no
		// rule keyed to those classes sets a width. The class still matters for the
		// rail's CONTENT (the project's own 52px rules, and the 'L' mark that
		// replaces the wordmark), so both are set: the property for the width, the
		// class for what goes in it.
		var sidebar = document.querySelector(".region-sidebar");
		if (!sidebar) {
		    return Promise.resolve(false);
		}
		var sc = sidebar.parentElement;
		var closed = (getComputedStyle(document.documentElement)
		    .getPropertyValue("--navsidebar-width-closed") || "52px").trim();
		var collapsed = sidebar.style.getPropertyValue("--sidebar-size").trim() === closed;
	
		if (collapsed) {
		    sidebar.style.setProperty("--sidebar-size", "232px");
		    if (sc) { sc.classList.add("mx-scrollcontainer-open"); }
		} else {
		    sidebar.style.setProperty("--sidebar-size", closed);
		    // `mx-scrollcontainer-shrink` is not in the model — ScrollBehavior is
		    // PerRegion on Atlas' layout and on this copy alike, so the marketplace
		    // widget must add it at runtime. Added here for the same reason.
		    if (sc) {
		        sc.classList.add("mx-scrollcontainer-shrink");
		        sc.classList.remove("mx-scrollcontainer-open");
		    }
		}
		return Promise.resolve(collapsed);
	// END USER CODE
}
